17 Authorization/Authorization/urls.py
from django.contrib import admin
from django.urls import path
from info import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homedetail,name='homepage'),
    path('add/',views.add),
    # path('add/addrecord/', views.addrecord, name='addrecord'),
    path('update/<int:id>', views.update, name='update'),
    path('update/updaterecord/<int:id>', views.updaterecord, name='updaterecord'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('register', views.registeruser, name='register'),
    path('login',views.userlogin,name='login'),
    path('logout',views.logoutuser,name='logout'),
    path('task',views.createtask,name='createtask'),
    path('list',views.tasklist,name='tasklist')


]

17 Authorization/info/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class StudentData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    stu_name=models.CharField(max_length=30)
    stu_division=models.CharField(max_length=30)
    stu_stream=models.CharField(max_length=20)
    
class Tasks(models.Model):
    task_name=models.CharField(max_length=100)
    task_date=models.DateField(auto_now=True)

17 Authorization/info/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        

17 Authorization/info/views.py
from django.shortcuts import render,redirect
from .models import StudentData,Tasks
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required,permission_required

def registeruser(request):
   if request.user.is_authenticated:
        return render(request,'home.html',{'name':request.user.username})
   form=CreateUserForm()
   if request.method=='POST':
      form=CreateUserForm(request.POST)
      if form.is_valid():
         form.save()
         user=form.cleaned_data.get('username')
         messages.success(request,'Account Created Successfully for ' + user)
         return redirect('login')
   context={'form':form}
   return render(request,'register.html',context)

def userlogin(request):
   if request.user.is_authenticated:
        return redirect('home')
   if request.method=='POST':
      username=request.POST.get('username')
      password=request.POST.get('password')
      
      user=authenticate(request,username=username,password=password)
      if user is not None:
         login(request,user)
         return redirect('/')
      else:
         messages.info(request,'username and password is incorrect')
    
   return render(request,'login.html')

def logoutuser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def homedetail(request):
    data=StudentData.objects.all()
    context={'data':data}
    return render(request,'home.html',context)

# def add(request):
#   return render(request,'add.html')
  
# def addrecord(request):
#   stu_name = request.POST['stu_name']
#   stu_division = request.POST['stu_division']
#   stu_stream=request.POST['stu_stream']
#   member = StudentData(stu_name=stu_name, stu_division=stu_division,stu_stream=stu_stream)
#   member.save()
#   return redirect('/')

def add(request):
    if request.method=="POST":
        stu_name=request.POST.get('stu_name')
        stu_division=request.POST.get('stu_division')
        stu_stream=request.POST.get('stu_stream')
        data=StudentData(stu_name=stu_name,stu_division=stu_division,stu_stream=stu_stream)
        data.save()
        return redirect('/')

    return render(request,'add.html')

@login_required(login_url='login')
def delete(request, id):
  member = StudentData.objects.get(id=id)
  member.delete()
  return redirect('/')

@login_required(login_url='login')
def update(request, id):
  data = StudentData.objects.get(id=id)
  context = {
    'data': data,
  }
  return render(request,'update.html',context)
  
def updaterecord(request, id):
  name = request.POST['name']
  division = request.POST['division']
  stream=request.POST['stream']
  data = StudentData.objects.get(id=id)
#   data= StudentData(stu_name=name,stu_division=division,stu_stream=stream)
  data.stu_name=name
  data.stu_division = division
  data.stu_stream= stream
  data.save()
  return redirect('/')

def createtask(request):
    if request.method=="POST":
        task_name=request.POST.get('task_name')
        task_date=request.POST.get('task_date')
        data=Tasks(task_name=task_name,task_date=task_date)
        data.save()
        return redirect('createtask')

    return render(request,'createtask.html')

def tasklist(request):
   gettask=Tasks.objects.all()
   print(gettask)
   context={'getlist':gettask}
   # return redirect('createtask')
   return render(request,'viewtask.html',context)

17 Authorization/templates/add.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

<body>


<form action="" method='POST'>
{% csrf_token %}
    <p>Student</p>
    <input type="text" name="stu_name"><br><br>
    <input type="text" name="stu_division"><br><br>
    <input type="text" name="stu_stream"><br><br>

    <br><br>
    <input type="submit">

</form>
</body>
</html>

17 Authorization/templates/createtask.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<!DOCTYPE html>
<html>
<body>

<form action="" method='POST'>
{% csrf_token %}
    <p>Create Task</p>
    <input type="text" name="task_name"><br><br>
    <input type="text" name="task_date"><br><br>
    <input type="submit">
    {% if perms.info.view_tasks %}
    <button><a href="list">View Task</a></button>
    {% else %}
    <p>Permission Denied for View</p>
    {% endif %}


</form>

</body>
</html>

17 Authorization/templates/home.html
<!DOCTYPE html>
<html>
<body>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<nav>
<span class="hello-msg">Hello, {{request.user}}</span>
<span class="hello-msg"><a href="{% url 'logout' %}">Logout</a></span>
</nav>
<br><br>
<hr>
<h2>Student Info</h2>
{% comment %} <p></p> {% endcomment %}
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Division</th>
    <th>Stream</th>
    <th>Delete</th>
  </tr>
  {% for x in data %}
  <tr>
    <td><a href="update/{{ x.id }}">{{ x.id }}</a></td>
    <td>{{x.stu_name}}</td>
    <td>{{x.stu_division}}</td>
    <td>{{x.stu_stream}}</td>
    <td>{% if perms.info.delete_studentdata %}
    <a href="delete/{{ x.id }}"><button>Delete</button></a>    
    {% else %}
      <h5>You Cannot Delete</h5>
  </tr>
  {% endif %}
  {% endfor %}
</table>
<p>    {% if perms.info.add_studentdata %}
<a href="add/"><button>add student</button></a>
{% else %}
      <h5>You Cannot Add</h5>
 {% endif %}
</p>
<br>
<button><a href="task">Add Task</a></button>

</body>
</html>

17 Authorization/templates/login.html
<h3>Authentication Task</h3>
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                     {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		        {% for message in messages %}
                  <p id="messages">{{message}}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

17 Authorization/templates/register.html
<h2>Authentication Task</h2>


<!DOCTYPE html>
<html>

  <head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
      body,
      html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #7abecc !important;
      }

      .user_card {
        width: 350px;
        margin-top: auto;
        margin-bottom: auto;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

      }

      .form_container {
        margin-top: 20px;
      }

      #form-title {
        color: #fff;
      }

      .login_btn {
        width: 100%;
        background: #33ccff !important;
        color: white !important;
      }

      .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
      }

      .login_container {
        padding: 0 2rem;
      }

      .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
      }

      .input_user,
      .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
      }

    </style>

  </head>

  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">REGISTER ACCOUNT</h3>
          </div>
          <div class="d-flex justify-content-center form_container">

            <form method="post" action="">
            {% csrf_token %}
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                {{form.username}}
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                </div>
                {{form.email}}
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                {{form.password1}}
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                {{form.password2}}
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Register Account">
              </div>
            </form>
          </div>

           {{form.errors}}
           
          <div class="mt-4">
            <div class="d-flex justify-content-center links">
              Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
            </div> 
          </div>
        </div>
      </div>
    </div>
    <script>
      /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

      //Query All input fields
      var form_fields = document.getElementsByTagName('input')
      form_fields[1].placeholder = 'Username..';
      form_fields[2].placeholder = 'Email..';
      form_fields[3].placeholder = 'Enter password...';
      form_fields[4].placeholder = 'Re-enter Password...';


      for (var field in form_fields) {
        form_fields[field].className += ' form-control'
      }

    </script>
  </body>

</html>

17 Authorization/templates/update.html
<h1>Update member</h1>
{% comment %} <form action="{% url 'update' %}" method="POST"> {% endcomment %}
<form action="updaterecord/{{ data.id }}" method="post">
{% csrf_token %}
{% comment %} <input type="hidden" name="id" value="{{data.id}}"> {% endcomment %}
Student Name:<br>
<input name="name" value="{{ data.stu_name }}">
<br><br>
Student Division:<br>
<input name="division" value="{{ data.stu_division }}">
<br><br>
Student Stream:<br>
<input name="stream" value="{{ data.stu_stream}}">
<br><br>
<input type="submit" value="Submit">
</form>

17 Authorization/templates/viewtask.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<!DOCTYPE html>
<html>
<body>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<nav>
<span class="hello-msg">Hello, {{request.user}}</span>
<span class="hello-msg"><a href="{% url 'logout' %}">Logout</a></span>
</nav>
<br><br>
<hr>
<h2>Task List</h2>
<table>
  <tr>
    <th>Id</th>
    <th>Task Name</th>
    <th>Date</th>
  </tr>
  <table>
  {% for x in getlist %}
  <tr>
  <td>{{x.id}}</td>
  <td>{{x.task_name}}</td>
  <td>{{x.task_date}}</td>
  </tr>
  {% endfor %}
</table>
<br>
<button><a href="/">Back to Home</a></button>
</body>
</html>